
#include <gtkmm.h>
#include <gtkmmconfig.h>
#include <sigc++/sigc++.h>
#include <gtkmm/accelgroup.h>
#include <gtkmm/image.h>
#include <gtkmm/window.h>
#include <gtkmm/stockid.h>
#include <gtkmm/drawingarea.h>

#include "control.h"
#include "zoomraster.h"
#include "Observer.h"
#include "Model.h"
#include "abmtools.h"

extern Model *theModel;
extern Observer *theObserver;

Control::Control(Observer *obs, int xsize, int ysize) : Gtk::Window(Gtk::WINDOW_TOPLEVEL)
{
    observer = obs;

    const char *forward_xpm[] = {
        /* columns rows colors chars-per-pixel */
        "48 48 200 2 ",
        "   c #71736D",
        ".  c #747670",
        "X  c #787A74",
        "o  c #7A7C77",
        "O  c #7B7D77",
        "+  c #7C7E78",
        "@  c #7F817B",
        "#  c #83857F",
        "$  c #858782",
        "%  c #868882",
        "&  c #868883",
        "*  c #878983",
        "=  c #878884",
        "-  c #8A8C86",
        ";  c #8D8F8A",
        ":  c #8E908A",
        ">  c #8E908B",
        ",  c #8F918C",
        "<  c #90918C",
        "1  c #91948D",
        "2  c #959891",
        "3  c #979893",
        "4  c #999B95",
        "5  c #999B97",
        "6  c #9A9B97",
        "7  c #9A9C97",
        "8  c #9B9D97",
        "9  c #9A9B98",
        "0  c #9B9D98",
        "q  c #9C9F98",
        "w  c #9EA09A",
        "e  c #9FA19B",
        "r  c #9FA39B",
        "t  c #A0A39C",
        "y  c #A0A29D",
        "u  c #A0A29E",
        "i  c #A4A6A0",
        "p  c #A4A7A0",
        "a  c #A4A7A1",
        "s  c #A5A9A1",
        "d  c #A6A9A2",
        "f  c #A6A8A3",
        "g  c #A7A8A3",
        "h  c #A7AAA3",
        "j  c #A6A8A4",
        "k  c #A7A9A4",
        "l  c #A7A9A5",
        "z  c #A8AAA3",
        "x  c #A9AAA7",
        "c  c #AAACA7",
        "v  c #ABAEA7",
        "b  c #ADAFA9",
        "n  c #ADB0A9",
        "m  c #AFB2AB",
        "M  c #AFB0AC",
        "N  c #AFB2AC",
        "B  c #B1B2AF",
        "V  c #B2B5AD",
        "C  c #B2B5AE",
        "Z  c #B3B5AF",
        "A  c #B3B7B0",
        "S  c #B4B6B0",
        "D  c #B5B6B1",
        "F  c #B5B6B2",
        "G  c #B4B7B2",
        "H  c #B6B8B2",
        "J  c #B6B9B2",
        "K  c #B7B8B5",
        "L  c #B8B9B5",
        "P  c #B8BBB4",
        "I  c #B8BBB5",
        "U  c #B9BBB5",
        "Y  c #BABDB6",
        "T  c #BCBFB8",
        "R  c #BCC0B9",
        "E  c #BFC1BB",
        "W  c #C0C0BD",
        "Q  c #C1C2BF",
        "!  c #CBCCC8",
        "~  c #CBCDC8",
        "^  c #CACCC9",
        "/  c #CBCDC9",
        "(  c #CCCDCA",
        ")  c #CDCDCA",
        "_  c #CDCECA",
        "`  c #CDCECB",
        "'  c #CECFCC",
        "]  c #CECECD",
        "[  c #CFCFCD",
        "{  c #CFD1CB",
        "}  c #CFD2CC",
        "|  c #D3D7CF",
        " . c #D3D4D1",
        ".. c #D6D7D5",
        "X. c #D5D8D1",
        "o. c #D5D9D1",
        "O. c #D5D9D2",
        "+. c #D6DAD2",
        "@. c #D7DAD3",
        "#. c #D7DBD3",
        "$. c #D7DBD4",
        "%. c #D9DCD5",
        "&. c #D9DDD6",
        "*. c #DADDD7",
        "=. c #DBDED7",
        "-. c #DADBD9",
        ";. c #DBDED8",
        ":. c #DCDFD9",
        ">. c #DCDEDA",
        ",. c #DDDDDC",
        "<. c #DDE0DA",
        "1. c #DEE1DA",
        "2. c #DEE1DB",
        "3. c #DEE0DC",
        "4. c #DFE1DD",
        "5. c #DFE2DC",
        "6. c #E0E3DD",
        "7. c #E1E3DD",
        "8. c #E0E3DE",
        "9. c #E1E3DE",
        "0. c #E1E4DE",
        "q. c #E2E4DF",
        "w. c #E2E3E0",
        "e. c #E2E3E1",
        "r. c #E2E5E0",
        "t. c #E3E5E0",
        "y. c #E3E6E1",
        "u. c #E3E4E2",
        "i. c #E4E6E1",
        "p. c #E4E5E3",
        "a. c #E4E7E2",
        "s. c #E5E7E2",
        "d. c #E7E7E6",
        "f. c #E5E8E3",
        "g. c #E6E8E3",
        "h. c #E6E8E4",
        "j. c #E6E9E4",
        "k. c #E7E9E4",
        "l. c #E7E9E5",
        "z. c #E8E9E7",
        "x. c #E9E9E7",
        "c. c #E8EAE6",
        "v. c #E9EBE7",
        "b. c gray91",
        "n. c gray92",
        "m. c #EAECE8",
        "M. c #EAECE9",
        "N. c #EBEDE9",
        "B. c #ECEDEA",
        "V. c #ECEEEA",
        "C. c #ECEEEB",
        "Z. c #EDEEEB",
        "A. c #ECECEC",
        "S. c #EDEEEC",
        "D. c #EDEFEC",
        "F. c #EEEFEC",
        "G. c #EEEEED",
        "H. c #EEF0ED",
        "J. c #EFF0ED",
        "K. c #EFF0EE",
        "L. c #EFF1EE",
        "P. c #F0F1EE",
        "I. c #F0F2EF",
        "U. c #F0F1F0",
        "Y. c #F1F2F0",
        "T. c #F1F2F1",
        "R. c #F2F3F0",
        "E. c #F2F2F1",
        "W. c #F2F3F1",
        "Q. c #F3F4F1",
        "!. c #F3F4F2",
        "~. c #F4F5F3",
        "^. c #F4F4F4",
        "/. c #F5F5F4",
        "(. c #F5F6F4",
        "). c #F5F6F5",
        "_. c #F6F7F5",
        "`. c #F6F7F6",
        "'. c #F7F7F6",
        "]. c #F7F8F6",
        "[. c #F8F8F7",
        "{. c #F8F9F8",
        "}. c #F9F9F8",
        "|. c #F9F9F9",
        " X c #F9FAF9",
        ".X c #FAFAF9",
        "XX c gray98",
        "oX c #FAFBFA",
        "OX c #FBFBFA",
        "+X c #FBFBFB",
        "@X c #FBFCFB",
        "#X c #FCFCFB",
        "$X c gray99",
        "%X c #FCFDFC",
        "&X c #FDFDFC",
        "*X c #FDFDFD",
        "=X c #FDFEFD",
        "-X c #FEFEFE",
        ";X c white",
        ":X c None",
        /* pixels */
        ":X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:XY T :X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:XY T :X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:XY '.} R :X:X:X:X:X:X:X:X:X:X:X:X:X:XY '.{ R :X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:XJ ;X@XB.R Y :X:X:X:X:X:X:X:X:X:X:X:XJ ;X+XM.E U :X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:XC ;X&.B.@X:.J :X:X:X:X:X:X:X:X:X:X:XC ;X@.B.#X2.J :X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:Xm ;X@.@.&.Q.].! C :X:X:X:X:X:X:X:X:Xm ;X@.&.7.'.[._ S :X:X:X:X:X:X:X:X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:Xv ;X@.| @.@.f.OXB.Y N :X:X:X:X:X:X:Xc ;X&.;.2.4.M.#XF.U C :X:X:X:X:X:X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:Xd ;X| @.@.%.:.2.H.;X4.b :X:X:X:X:X:Xz ;X:.2.7.q.s.h.Q.;X7.m :X:X:X:X:X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:Xa ;XX.$.%.;.2.2.4.f.].+X! c :X:X:X:Xt ;X2.q.q.f.f.m.M.H.@X+X_ x :X:X:X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:Xt ;X@.&.;.:.2.q.q.f.h.F.$XY.S d :X:Xt ;Xq.u.f.h.m.M.H.H.Y.'.;X'.S d :X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:X0 ;X&.&.2.4.q.q.s.f.c.m.B.].;Xu.d d w ;Xs.f.c.m.B.H.H.Q.Q.].'.$X;Xd.a w :X:X:X:X:X:X",
        ":X:X:X:X:X:X4 ;X;.2.4.7.q.s.f.c.M.B.H.H.Y.$X+X! 4 ;Xf.m.M.B.H.P.Q.^.].].+X$X;X;X;X[ w :X:X:X:X:X",
        ":X:X:X:X:X:X2 ;X2.2.q.q.f.f.k.N.M.F.H.H.'.$X+X^ 2 ;Xc.B.H.H.Y.~.'.'.+X+X@X;X;X;X$X_ r :X:X:X:X:X",
        ":X:X:X:X:X:X1 ;X6.q.q.f.f.c.N.N.F.P.Y.+X;Xe.0 U 1 ;XB.H.H.Q.Q.'.'.[.+X;X;X;X;Xs.0 K |.:X:X:X:X:X",
        ":X:X:X:X:X:X: ;Xq.q.f.f.c.m.B.P.P.'.;XY.a a b.:X: ;XH.P.Q.Q.].{.+X;X;X;X;X^.l d b.:X:X:X:X:X:X:X",
        ":X:X:X:X:X:X- ;Xq.f.f.m.m.B.H.I.+X+XW 3 [ :X:X:X- ;XP.~.'.'.+X+X$X;X;X$XE 3 [ :X:X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:X% ;Xf.h.c.M.F.F.'.;X-.< S $X:X:X:X:X% ;XQ.'.].+X@X;X;X;X,.< S +X:X:X:X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:X# ;Xh.M.M.B.^.+XF.9 r b.:X:X:X:X:X:X$ ;X].{.+X@X;X;XY.9 r b.:X:X:X:X:X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:X@ ;Xh.M.H.+X+XS , [ :X:X:X:X:X:X:X:X@ ;X].+X;X;X+XS , [ :X:X:X:X:X:X:X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:X+ ;XM.'.;X .$ B +X:X:X:X:X:X:X:X:X:XO ;X+X;X;X..% B $X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:XX ;X;Xh.; 9 n.:X:X:X:X:X:X:X:X:X:X:XX ;X;Xn.; 9 b.:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:X. [.l & [ :X:X:X:X:X:X:X:X:X:X:X:X:X. +Xx = | :X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:X  + b ;X:X:X:X:X:X:X:X:X:X:X:X:X:X:X  + N ;X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:X:Xb.:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:Xb.:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X",
        ":X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X:X"
    };

    Glib::RefPtr<Gdk::Pixbuf> pixF = Gdk::Pixbuf::create_from_xpm_data(forward_xpm);
    Gtk::Image *imgF = new Gtk::Image(pixF);
    btRun = Gtk::manage(new class Gtk::ToolButton(*imgF, ""));

    const char *play_xpm[] = {
        /* columns rows colors chars-per-pixel */
        "48 48 159 2 ",
        "   c #6B6D67",
        ".  c #6D6F69",
        "X  c #71736D",
        "o  c #747670",
        "O  c #777974",
        "+  c #787A74",
        "@  c #7B7D78",
        "#  c #7C7E78",
        "$  c #7E807A",
        "%  c #7F817B",
        "&  c #82847E",
        "*  c #83857F",
        "=  c #868882",
        "-  c #878983",
        ";  c #898A85",
        ":  c #8A8B86",
        ">  c #8A8C86",
        ",  c #8E908A",
        "<  c #90928C",
        "1  c #91948D",
        "2  c #939490",
        "3  c #959891",
        "4  c #969893",
        "5  c #979993",
        "6  c #989995",
        "7  c #999B95",
        "8  c #9A9B97",
        "9  c #9B9E99",
        "0  c #9C9F98",
        "q  c #9C9E9A",
        "w  c #9EA09C",
        "e  c #A0A39C",
        "r  c #A2A29F",
        "t  c #A2A59E",
        "y  c #A3A59F",
        "u  c #A3A6A0",
        "i  c #A4A5A0",
        "p  c #A4A6A0",
        "a  c #A4A7A1",
        "s  c #A7A8A3",
        "d  c #A7AAA3",
        "f  c #A8A9A4",
        "g  c #ABAEA7",
        "h  c #AAACA8",
        "j  c #ACADA8",
        "k  c #ACAFA8",
        "l  c #AFB1AB",
        "z  c #AFB2AB",
        "x  c #AFB0AD",
        "c  c #B1B2AE",
        "v  c #B2B5AE",
        "b  c #B2B4AF",
        "n  c #B3B5AF",
        "m  c #B1B3B0",
        "M  c #B6B9B2",
        "N  c #B7BAB2",
        "B  c #B6B8B4",
        "V  c #B6B8B5",
        "C  c #B9BBB5",
        "Z  c #B8BAB6",
        "A  c #BABBB6",
        "S  c #BABDB6",
        "D  c #BABCB7",
        "F  c #BBBEB8",
        "G  c #BCBFB8",
        "H  c #BDBFB8",
        "J  c #BDBEB9",
        "K  c #BEBFBB",
        "L  c #BDC0BA",
        "P  c #C1C3BD",
        "I  c #C5C6C3",
        "U  c #C8CAC7",
        "Y  c #CCCFC9",
        "T  c #CCCECA",
        "R  c #CECFCC",
        "E  c #CCD0CA",
        "W  c #CFD0CD",
        "Q  c #D2D3D0",
        "!  c #D6D6D4",
        "~  c #D4D8D0",
        "^  c #D4D8D1",
        "/  c #D6DAD2",
        "(  c #D6DAD3",
        ")  c #D7DAD3",
        "_  c #D7D8D6",
        "`  c #D8DCD5",
        "'  c #DADDD6",
        "]  c #DBDED7",
        "[  c #DBDCD9",
        "{  c #DCDFD9",
        "}  c #DDDFDB",
        "|  c #DDDDDC",
        " . c #DDE0DA",
        ".. c #DEE1DB",
        "X. c #DFE1DB",
        "o. c #DFE1DD",
        "O. c #DFE2DC",
        "+. c #E1E3DE",
        "@. c #E1E4DF",
        "#. c #E1E2E0",
        "$. c #E3E3E1",
        "%. c #E4E5E1",
        "&. c #E4E6E1",
        "*. c #E4E5E3",
        "=. c #E5E7E2",
        "-. c #E6E7E4",
        ";. c #E6E8E4",
        ":. c #E7E8E4",
        ">. c #E7E9E4",
        ",. c #E9E9E7",
        "<. c #E8EAE6",
        "1. c #E9EAE6",
        "2. c #EAEBE9",
        "3. c #EBEBEA",
        "4. c #EBECE8",
        "5. c #EAECE9",
        "6. c #EBECE9",
        "7. c #ECEDEB",
        "8. c #EDEDEB",
        "9. c #ECEEEB",
        "0. c #EDEEEB",
        "q. c #EDEDEC",
        "w. c #EEEEED",
        "e. c #EFF0ED",
        "r. c #F0F0EE",
        "t. c #F0F1EE",
        "y. c #F0F1EF",
        "u. c #F1F1F0",
        "i. c #F1F2F0",
        "p. c #F1F3F0",
        "a. c #F2F3F1",
        "s. c #F3F3F2",
        "d. c #F3F4F2",
        "f. c #F4F5F3",
        "g. c #F5F5F3",
        "h. c #F5F5F4",
        "j. c gray96",
        "k. c #F6F7F5",
        "l. c #F6F7F6",
        "z. c #F7F7F6",
        "x. c #F7F8F6",
        "c. c #F7F8F7",
        "v. c #F8F8F7",
        "b. c #F8F9F7",
        "n. c #F8F9F8",
        "m. c #F9FBF9",
        "M. c #FAFAF9",
        "N. c #FAFBFA",
        "B. c #FBFBFA",
        "V. c #FBFBFB",
        "C. c #FBFCFB",
        "Z. c gray99",
        "A. c #FCFDFC",
        "S. c #FDFDFC",
        "D. c #FDFDFD",
        "F. c #FDFEFD",
        "G. c #FEFEFE",
        "H. c white",
        "J. c None",
        /* pixels */
        "J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.H F J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.S [ L J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.S H.h.E H J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.S H.h.H.7.P H J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.S H.6.6.h.Z.o.L J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.M H.1.-.%.-.c.h.Y A J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.v H.%.%.+.X.[ >.C.6.L M J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.l H.*.+.X.X.] ( ( 6.C.X.v J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.g H.+.X.{ ] / ~ ~ /  .d.n.T x J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.d H.X.{ ] / ~ ~ / / ] X.>.C.y.A l J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.p H.{ ] / ~ ~ / _  . .O.@.=.d.H.*.h f J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.e H.] / ~ ~ / /  .X.O.@.*.=.>.6.c.V.~ p J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.0 H./ ~ ~ / ]  . .X.@.&.=.1.6.7.w.f.H.v.A t J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.6 H.~ ~ / _ ]  .X.O.&.>.<.6.7.e.a.a.h.m.H.w.f e J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.4 H.~ ( (  . .O.@.&.>.>.6.e.e.y.d.k.c.A.H.w.u m J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.1 H./  .(  .O.@.&.>.<.6.e.e.y.d.c.n.H.n.V t | J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J., H.]  . .O.@.&.>.>.6.6.e.y.d.c.A.A.W 6 I J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.> H.]  . .@.*.;.<.6.6.e.d.d.C.H.*.4 c h.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.- H...O.O.&.>.>.6.w.e.a.h.H.a.t w *.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.* H.O.O.&.>.<.6.w.e.d.V.Z.H < U J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.% H.O.&.>.<.6.7.e.h.H._ : x m.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.# H.&.;.<.<.e.h.H.3.2 9 2.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.+ H.>.>.2.y.m.c.h : Y J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.o H.1.w.c.H.U # m H.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.X H.d.H.o.* 8 u.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.. H.a.6 = ! J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.  A O V J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.@ 9 h.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.",
        "J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J.J."
    };

    Glib::RefPtr<Gdk::Pixbuf> pixY = Gdk::Pixbuf::create_from_xpm_data(play_xpm);
    Gtk::Image *imgY = new Gtk::Image(pixY);
    btStep = Gtk::manage(new class Gtk::ToolButton(*imgY, ""));

    const char * world_xpm[] = {
        "24 24 106 2",
        "  	c None",
        ". 	c #C9AB50",
        "+ 	c #B76B58",
        "@ 	c #B1565B",
        "# 	c #BD8056",
        "$ 	c #328B14",
        "% 	c #404040",
        "& 	c #107010",
        "* 	c #207000",
        "= 	c #7F4000",
        "- 	c #876B88",
        "; 	c #71569B",
        "> 	c #9D8076",
        ", 	c #A52B60",
        "' 	c #990066",
        ") 	c #800080",
        "! 	c #206020",
        "~ 	c #406000",
        "{ 	c #FF0000",
        "] 	c #452BC0",
        "^ 	c #1900E6",
        "/ 	c #AE4B5C",
        "( 	c #602060",
        "_ 	c #186818",
        ": 	c #306800",
        "< 	c #BF2000",
        "[ 	c #664BA4",
        "} 	c #452BC1",
        "| 	c #ABA247",
        "1 	c #889C38",
        "2 	c #659628",
        "3 	c #649628",
        "4 	c #649528",
        "5 	c #008000",
        "6 	c #8D9A3E",
        "7 	c #468D1F",
        "8 	c #0E3881",
        "9 	c #1320AC",
        "0 	c #095056",
        "a 	c #97A03C",
        "b 	c #268500",
        "c 	c #999300",
        "d 	c #0C4073",
        "e 	c #338600",
        "f 	c #CC9900",
        "g 	c #0D4073",
        "h 	c #06603A",
        "i 	c #1A8300",
        "j 	c #668C00",
        "k 	c #71559B",
        "l 	c #BAA74C",
        "m 	c #869A3A",
        "n 	c #528E28",
        "o 	c #ABA446",
        "p 	c #A3A341",
        "q 	c #A52B61",
        "r 	c #9C9E42",
        "s 	c #6E9235",
        "t 	c #B2A549",
        "u 	c #C39653",
        "v 	c #C08B54",
        "w 	c #BEA059",
        "x 	c #B39663",
        "y 	c #A88B6C",
        "z 	c #A6A146",
        "A 	c #BFA84D",
        "B 	c #C6AA4F",
        "C 	c #C8A050",
        "D 	c #C4804F",
        "E 	c #776930",
        "F 	c #C3804F",
        "G 	c #B3004C",
        "H 	c #9B883F",
        "I 	c #A09F44",
        "J 	c #B3A449",
        "K 	c #9EA13F",
        "L 	c #B0A646",
        "M 	c #23860F",
        "N 	c #6F8C00",
        "O 	c #1C8300",
        "P 	c #0D7013",
        "Q 	c #33404C",
        "R 	c #266019",
        "S 	c #4C4033",
        "T 	c #395026",
        "U 	c #3E431B",
        "V 	c #DE9900",
        "W 	c #388600",
        "X 	c #1A6026",
        "Y 	c #660099",
        "Z 	c #4D4033",
        "` 	c #43002D",
        " .	c #73204D",
        "..	c #238610",
        "+.	c #A79300",
        "@.	c #2A8500",
        "#.	c #13681D",
        "$.	c #4D2073",
        "%.	c #563839",
        "&.	c #589027",
        "*.	c #559123",
        "=.	c #408D1B",
        "-.	c #809A35",
        ";.	c #538900",
        ">.	c #A69300",
        ",.	c #7D8E00",
        "                                                ",
        "  . . . . + @ # $ % % & * = = $ . . . . - ; >   ",
        "  . . . . , ' @ $ ) ) ! ~ { { $ . . . . ] ^ ;   ",
        "  . . . . / , + $ ( ( _ : < < $ . . . . [ } -   ",
        "  | | | 1 2 2 2 3 4 4 4 5 5 5 $ . . . . . . .   ",
        "  6 6 6 7 8 9 0 a . . . b c c $ - ] [ . . . .   ",
        "  6 6 6 7 9 ^ d a . . . e f f $ ; ^ ] . . . .   ",
        "  6 6 6 7 0 g h a . . . i j j $ > k - . . . .   ",
        "  l l l m n n n o . . . a a a p . . . . . . .   ",
        "  @ ' q r s s s t . . . > ^ ^ . ; ^ ] . . . .   ",
        "  @ ' q r s s s t . . . > ^ ^ . ; ^ } . . . .   ",
        "  u # v r s s s t . . . w > > . x > y . . . .   ",
        "  6 6 6 z A A A B . . . C D D . . . . . . . .   ",
        "  6 6 6 z A E A B . . . F G G . . . . . . . .   ",
        "  6 6 6 z A H A B . . . D G G . . . . . . . .   ",
        "  6 6 6 I J J J K a a a a a a a a a a L . . .   ",
        "  6 6 6 6 6 6 6 M N N O P Q Q 5 R S T 3 . . .   ",
        "  6 6 6 6 6 U 6 M V V W X Y Y 5 Z `  .3 . . .   ",
        "  6 6 6 6 6 6 6 ..+.+.@.#.$.$.5 T  .%.3 . . .   ",
        "  6 6 6 6 6 6 6 &.7 7 7 *.*.*.=.5 5 5 3 . . .   ",
        "  6 6 6 6 6 6 6 6 6 6 6 | | | -.;.>.,.3 . . .   ",
        "  6 6 6 6 6 6 6 6 6 6 6 | | | -.N V >.3 . . .   ",
        "  6 6 6 6 6 6 6 6 6 6 6 | | | -.W N ;.3 . . .   ",
        "                                                "};


    Glib::RefPtr<Gdk::Pixbuf> pixW = Gdk::Pixbuf::create_from_xpm_data(world_xpm);
    Gtk::Image *imgW = new Gtk::Image(pixW);
    btView = Gtk::manage(new class Gtk::ToolButton(*imgW, ""));

    const char * graph_xpm[] = {
        "24 22 9 1",
        " 	c None",
        ".	c #000000",
        "+	c #FFFFFF",
        "@	c #8080FF",
        "#	c #0000FF",
        "$	c #FF8080",
        "%	c #FF0000",
        "&	c #000080",
        "*	c #800080",
        "........................",
        ".++++++++++++++++++++++.",
        ".++++++++++++++++++++++.",
        ".++++++++++++++++++++++.",
        ".+++++++++++++++++++++@.",
        ".++++++++++++++++++++@#.",
        ".++++++++++++++++++++#@.",
        ".+++++++++++++++++++#@+.",
        ".$$$$$$$+++++++++++@#++.",
        ".%%%%%%%%%$+++++++@#+++.",
        ".+++++++$$%%%$+++@#@+++.",
        ".+++++++++++$%$@##@++++.",
        ".+++++@@@++++@&#*++++++.",
        ".++++#########@$%%+++++.",
        ".++@#@+++++@@++++%%$+++.",
        ".+@#@+++++++++++++$%+++.",
        ".##@+++++++++++++++$%++.",
        ".#++++++++++++++++++%$+.",
        ".++++++++++++++++++++%%.",
        ".+++++++++++++++++++++%.",
        ".++++++++++++++++++++++.",
        "........................"};

    Glib::RefPtr<Gdk::Pixbuf> pixG = Gdk::Pixbuf::create_from_xpm_data(graph_xpm);
    Gtk::Image *imgG = new Gtk::Image(pixG);
    btGraph = Gtk::manage(new class Gtk::ToolButton(*imgG, ""));


    const char * photom_xpm[] = {
        "24 24 41 1",
        " 	c None",
        ".	c #B8B8B8",
        "+	c #8E8E80",
        "@	c #F1F1F1",
        "#	c #FFFFFF",
        "$	c #AAAAAA",
        "%	c #E3E3E3",
        "&	c #808080",
        "*	c #555555",
        "=	c #2B3939",
        "-	c #8E8E8E",
        ";	c #717163",
        ">	c #717171",
        ",	c #9CAA9C",
        "'	c #AAB8AA",
        ")	c #AAAA9C",
        "!	c #636363",
        "~	c #718071",
        "{	c #D4D4D4",
        "]	c #9C9C9C",
        "^	c #636355",
        "/	c #637163",
        "(	c #393939",
        "_	c #1C1C1C",
        ":	c #474747",
        "<	c #808E80",
        "[	c #0E0E0E",
        "}	c #0E1C1C",
        "|	c #1C2B2B",
        "1	c #2B2B2B",
        "2	c #474739",
        "3	c #475547",
        "4	c #808071",
        "5	c #556355",
        "6	c #C6C6C6",
        "7	c #555547",
        "8	c #B8B8AA",
        "9	c #8E8080",
        "0	c #E3D4D4",
        "a	c #D4C6C6",
        "b	c #D4D4C6",
        "                        ",
        "                        ",
        "                        ",
        "         .++++.         ",
        "        .+@@@#+$%       ",
        "      &*=+####+=.       ",
        "   -===;$&>>>>>,====&   ",
        "   ='$$$--&&&&&&,)))=   ",
        "   =$>!.$~+>>>;*!>+&=   ",
        "   =$;!${!]--+^**+!>=   ",
        "   =$/!*;-(__:+/*<!>=   ",
        "   =$/!*-([}__:+*&!>=   ",
        "   =$!!!-_}{$|1+*~!>=   ",
        "   =$/!/+__$111<2>!>=   ",
        "   =$/!*-:_|1-3&(!!>=   ",
        "   =$!!*4+:113<(1!~>=   ",
        "  %=)!!!*5>&&^(1*!~;={  ",
        "  6=<-&4>;!*7::;~--&=$% ",
        "  6!================:]% ",
        "  %8-&&&&&&&>>>>>>&9]6  ",
        "    0{a66a{{{{{a6b{0    ",
        "                        ",
        "                        ",
        "                        "};

    Glib::RefPtr<Gdk::Pixbuf> pixP = Gdk::Pixbuf::create_from_xpm_data(photom_xpm);
    Gtk::Image *imgP = new Gtk::Image(pixP);
    btPict = Gtk::manage(new class Gtk::ToolButton(*imgP, ""));

/* XPM */
    const char *quit_xpm[] = {
        /* columns rows colors chars-per-pixel */
        "48 48 179 2 ",
        "   c #7D0101",
        ".  c #7E2928",
        "X  c #4E4E4E",
        "o  c #535353",
        "O  c #575955",
        "+  c #595B57",
        "@  c #5C5D5B",
        "#  c #5E605C",
        "$  c #62645F",
        "%  c #636363",
        "&  c #6C6C6B",
        "*  c #666864",
        "=  c #6F716D",
        "-  c #71736F",
        ";  c #737373",
        ":  c #7B7C7B",
        ">  c #797A77",
        ",  c #850303",
        "<  c #840C0A",
        "1  c #8B0E0A",
        "2  c #9D0000",
        "3  c #9E0D05",
        "4  c #980908",
        "5  c #931508",
        "6  c #A40101",
        "7  c #AB0A05",
        "8  c #AB0E0C",
        "9  c #A80402",
        "0  c #B80100",
        "q  c #B00F07",
        "w  c #B4140A",
        "e  c #B21E0D",
        "r  c #B81D0C",
        "t  c #BE1717",
        "y  c #BD210D",
        "u  c #912626",
        "i  c #9D3332",
        "p  c #A72827",
        "a  c #B22827",
        "s  c #B22828",
        "d  c #C00606",
        "f  c #C20C06",
        "g  c #C30C0C",
        "h  c #CC0B0B",
        "j  c #CA0707",
        "k  c #D50D0C",
        "l  c #C31D0A",
        "z  c #D2160D",
        "x  c #C91818",
        "c  c #DA1C1C",
        "v  c #D61815",
        "b  c #E21F1F",
        "n  c #CA2B0F",
        "m  c #C42D11",
        "M  c #C92817",
        "N  c #C52514",
        "B  c #D22310",
        "V  c #CA3316",
        "C  c #C93718",
        "Z  c #CC3D17",
        "A  c #D63D1B",
        "S  c #D13717",
        "D  c #E2311C",
        "F  c #E1381A",
        "G  c #DD2E2E",
        "H  c #DD3F23",
        "J  c #CA3434",
        "K  c #D83A3A",
        "L  c #EF2A2A",
        "P  c #E82625",
        "I  c #F0332B",
        "U  c #F03C3C",
        "Y  c #D5461A",
        "T  c #DD451D",
        "R  c #D6491E",
        "E  c #E1471E",
        "W  c #DF4923",
        "Q  c #DD4123",
        "!  c #DE522F",
        "~  c #E34E24",
        "^  c #E54526",
        "/  c #E25124",
        "(  c #EA512B",
        ")  c #EE5A2E",
        "_  c #F2572F",
        "`  c #E6473A",
        "'  c #F24835",
        "]  c #E85C39",
        "[  c #F25D34",
        "{  c #BB4B4A",
        "}  c #AE5959",
        "|  c #BE5B5A",
        " . c #D44746",
        ".. c #DD5B43",
        "X. c #C45C5C",
        "o. c #D85858",
        "O. c #F24E4E",
        "+. c #E15A5A",
        "@. c #F25454",
        "#. c #DC665B",
        "$. c #F66744",
        "%. c #E66955",
        "&. c #F46558",
        "*. c #F57159",
        "=. c #D56868",
        "-. c #DE6F6F",
        ";. c #DB746F",
        ":. c #E06D60",
        ">. c #F26D6D",
        ",. c #F47A6A",
        "<. c #E47E7A",
        "1. c #E67877",
        "2. c #7D807C",
        "3. c #81827F",
        "4. c #EA807E",
        "5. c #838483",
        "6. c #878885",
        "7. c #888987",
        "8. c #8C8C8B",
        "9. c #8F908F",
        "0. c #939393",
        "q. c #979895",
        "w. c #989A96",
        "e. c #9B9B9B",
        "r. c #BD9391",
        "t. c #9EA09D",
        "y. c #A1A29E",
        "u. c #A4A4A4",
        "i. c #AAACA7",
        "p. c #ABABAB",
        "a. c #AFB2AC",
        "s. c #B0B1AE",
        "d. c #B3B4B3",
        "f. c #B6B8B3",
        "g. c #BABCB7",
        "h. c #BDBDBD",
        "j. c #CC9796",
        "k. c #D59797",
        "l. c #D79898",
        "z. c #D99B9B",
        "x. c #E48686",
        "c. c #EC8684",
        "v. c #F68382",
        "b. c #F68D8C",
        "n. c #F68A85",
        "m. c #CABCB8",
        "M. c #BEC0BA",
        "N. c #C0C3BD",
        "B. c #C4C6C1",
        "V. c #C6C9C4",
        "C. c #C9CBC5",
        "Z. c #CECECD",
        "A. c #D6C2C0",
        "S. c #CED0CB",
        "D. c #D1D3CE",
        "F. c #D4D5D2",
        "G. c #D7D9D5",
        "H. c #D8D9D6",
        "J. c #DCDDDA",
        "K. c #E4C8C7",
        "L. c #E6CCCB",
        "P. c #E8CCCB",
        "I. c #ECD0CF",
        "U. c #DFE0DD",
        "Y. c #E0E1DE",
        "T. c #E4E5E2",
        "R. c #E7E8E6",
        "E. c #E9EAE7",
        "W. c #EBECEA",
        "Q. c #ECE6E5",
        "!. c #F2EBEA",
        "~. c #EFF0EF",
        "^. c #F0F1EF",
        "/. c #F5F5F4",
        "(. c #F7F8F7",
        "). c #F8F8F7",
        "_. c #FBFBFB",
        "`. c #F8F1F1",
        "'. c None",
        /* pixels */
        "'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.",
        "'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.",
        "'.'.+ + @ @ + + o @ o @ @ @ @ O O @ # % % & ; : 5.6.6.6.6.6.5.: ; '.'.'.'.'.'.'.'.'.'.'.'.'.'.'.",
        "'.@ B.u.6.: ; ; & & % o @ @ @ @ @ @ @ % & : W.W.W.~.W./.^.W.W.W.U.- '.'.'.'.'.'.'.'.'.'.'.'.'.'.",
        "'.@ V.p.8.5.: ; & % @ o X X X X X X o @ % : /./././.).).).)././.^.: '.'.'.'.'.'.'.'.'.'.'.'.'.'.",
        "'.@ Z.p.8.7.: ; & % @ o X X X X X X o @ & 8./.(._._._._._._.).).^.5.'.'.'.'.'.'.'.'.'.'.'.'.'.'.",
        "'.@ V.d.0.7.3.> & & @ o X X X X X o o @ & 8.(.(._._._._._._._.)./.6.'.'.'.'.'.'.'.'.'.'.'.'.'.'.",
        "'.@ Z.d.0.8.5.: & & % o X X X X X X o @ & 9.(.(._._._._._._._.)./.8.'.'.'.'.'.'.'.'.'.'.'.'.'.'.",
        "'.@ Z.d.0.9.5.: ; & % @ o X X X X o o @ & 0.).)._._._._._._._._./.8.'.'.'.'.'.'.'.'.'.'.'.'.'.'.",
        "'.@ Z.f.e.9.7.: ; ; % @ o X X X X o o @ ; 0.).)._._._._._._._._./.8.'.'.'.'.'.'.'.'.'.'.'.'.'.'.",
        "'.@ Z.h.e.0.7.5.: & & @ o o X X X o o % & 0.).)._._._._._._._._./.9.'.'.'.'.'.'.'.'.'.'.'.'.'.'.",
        "'.@ Z.g.e.0.8.5.: ; & % o X X X X X o @ ; 0.).)._._._._._._._.)./.8.'.'.'.'.'.'.'.'.'.'.'.'.'.'.",
        "'.@ Z.h.y.q.9.7.: ; & % @ o X X X X o % - 0./.)._._._._._._._._.P.i 7 8 '.'.'.'.'.'.'.'.'.'.'.'.",
        "'.@ F.h.u.e.9.7.: : & % @ o X X X o o @ - 9.(.)._._._._._._._.z.7 ^ ) ~ w '.'.'.'.'.'.'.'.'.'.'.",
        "'.@ Z.h.u.e.0.8.5.: ; % % o o X X o o % ; 0._._._._._._._._.I.8 ( ,.b.&.W 6 '.'.'.'.'.'.'.'.'.'.",
        "'.@ Z.h.u.t.0.9.5.: ; & % @ o X X o o @ ; 0./._._._._._._.`.s ^ *.v.O.v.) 6 '.'.'.'.'.'.'.'.'.'.",
        "'.@ Z.h.u.u.0.0.8.: : & % @ o X o X o @ & 0./.).)._._._._.X.M $.b.U L ' H 9 '.'.'.'.'.'.'.'.'.'.",
        "'.% Z.h.p.u.e.0.8.: : & % % o X X ; h.p.: 0.R.W.`.).(.(.l.w [ b.@.L I _ w '.'.'.'.'.'.'.'.'.'.'.",
        "'.% Z.h.p.u.e.0.8.5.: & & % o o o & Z.Z.Z.e.Y.R.~././.L.8 ( ,.>.P P _ M 9 '.'.'.'.'.'.'.'.'.'.'.",
        "'.% Z.h.p.p.e.e.8.5.: ; & % @ o X o @ u.H.h.U.W.~.`.!.s A &.4.P b ^ H 9 '.'.'.'.'.'.'.'.'.'.'.'.",
        "'.% Z.h.p.p.e.0.0.5.5.; & % @ o X X o d.H.e.U.R.~./.X.N ] c.G v D ~ 9 6 6 6 6 6 9 6 6 6 6 '.'.'.",
        "'.% Z.h.p.p.u.e.0.5.5.: ; % % o X o 5.F.e.0.Y.R.^.k.q / 1. .v v / / / / / / / / / / / W V 7 '.'.",
        "'.@ Z.h.p.p.u.e.0.8.5.: ; & % @ o % Z.e.; 0.U.W.K.8 A =.o.h -.x.x.x.x.x.x.x.x.x.x.x.x.x.%.V 6 '.",
        "'.@ F.h.p.p.p.u.e.8.5.: ; & % @ @ h.e.@ ; 0.U.R.{ y A o.g d d d d d d d d 0 d f 0 g d x  .Y 6 '.",
        "'.% Z.h.p.p.p.u.e.9.7.: ; & % @ : 0.o % ; 0.U.W.K.8 Z l 0 0 =.t 0 0 0 0 0 0 0 0 0 0 0 0 n m 6 '.",
        "'.# F.h.p.p.p.u.e.0.8.5.: ; % % @ o o % ; 0.U.R.^.k.7 Y f 0 J ;.R Y Y Y Y Y Y Y Y Y Y Y m 7 '.'.",
        "'.@ Z.h.p.p.p.u.e.e.8.5.: ; & % @ o o % > 0.U.W.^./.| r S d d o.#.Z 2 2 6 2 2 2 2 2 2 2 2 '.'.'.",
        "'.% Z.h.p.p.p.p.e.e.0.5.5.; & % @ o o % > 0.U.W.^./.!.p n S j g -...m 4 '.'.'.'.'.'.'.'.'.'.'.'.",
        "'.@ Z.h.p.p.p.p.u.e.0.8.: : & % @ @ @ % ; 0.T.W.W././.L.3 Y B j c 4.! y 4 '.'.'.'.'.'.'.'.'.'.'.",
        "'.@ Z.h.p.p.p.p.u.e.0.8.5.: ; & % @ @ % > q.Y.W.~./././.j.3 T z j K ;.W 3 '.'.'.'.'.'.'.'.'.'.'.",
        "'.% Z.h.p.p.p.p.u.e.0.8.5.: ; & % @ @ % : q.H.T.~././././.} e E k j +.%.C , '.'.'.'.'.'.'.'.'.'.",
        "'.# Z.h.p.p.p.p.p.u.e.0.5.5.: & & % % & : q.B.G.R.~./.~.~.Q.u V D k G 4.E , '.'.'.'.'.'.'.'.'.'.",
        "'.@ Z.h.p.p.p.p.p.u.e.9.8.5.: ; = & & ; 5.e.d.V.J.W.~.~.~.W.A.< T D v ` Z   '.'.'.'.'.'.'.'.'.'.",
        "'.% F.h.p.p.p.p.p.u.u.0.8.5.: : ; ; ; : 9.e.d.B.H.R.W.W.W.E.R.r.1 C ~ Y 5 '.'.'.'.'.'.'.'.'.'.'.",
        "'.@ Z.h.p.p.p.p.p.u.u.0.9.8.5.5.2.2.7.9.e.u.g.Z.J.T.T.R.R.R.Y.J.m.. < < '.'.'.'.'.'.'.'.'.'.'.'.",
        "'.% Z.h.p.p.p.p.p.p.u.e.0.9.8.8.0.9.8.q.u.f.V.F.J.Y.T.Y.Y.Y.U.H.D.2.'.'.'.'.'.'.'.'.'.'.'.'.'.'.",
        "'.# Z.h.d.p.p.p.p.s.u.u.e.e.e.e.6.9.t.a.M.C.F.U.J.J.J.J.J.J.J.F.D.> '.'.'.'.'.'.'.'.'.'.'.'.'.'.",
        "'.# Z.h.p.p.p.p.p.s.p.u.p.u.7.8.w.a.M.C.F.F.F.G.H.H.G.G.G.G.F.S.C.; '.'.'.'.'.'.'.'.'.'.'.'.'.'.",
        "'.# Z.h.p.p.p.p.s.s.h.f.8.5.e.p.M.N.S.D.D.F.F.F.F.F.F.F.D.D.S.S.C.= '.'.'.'.'.'.'.'.'.'.'.'.'.'.",
        "'.# F.h.p.p.p.d.h.h.0.5.0.p.h.h.C.C.S.C.S.S.S.S.Z.Z.Z.Z.S.S.S.C.C.& '.'.'.'.'.'.'.'.'.'.'.'.'.'.",
        "'.# Z.h.p.p.h.V.u.5.w.i.f.M.V.V.C.C.C.C.C.C.C.C.C.C.C.C.C.C.C.V.N.* '.'.'.'.'.'.'.'.'.'.'.'.'.'.",
        "'.# Z.B.h.C.i.7.e.p.f.M.N.B.N.B.N.V.V.N.B.V.B.V.V.N.V.V.V.V.N.N.N.% '.'.'.'.'.'.'.'.'.'.'.'.'.'.",
        "'.# Z.Z.g.e.y.a.f.g.M.M.N.N.M.N.N.N.N.M.N.N.M.N.N.N.N.M.M.N.M.M.N.# '.'.'.'.'.'.'.'.'.'.'.'.'.'.",
        "'.@ B.i.i.a.f.g.g.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.M.# '.'.'.'.'.'.'.'.'.'.'.'.'.'.",
        "'.@ O O O O O O + + + + + @ + + # + + @ + @ + @ + @ + + + + + + O # '.'.'.'.'.'.'.'.'.'.'.'.'.'.",
        "'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.",
        "'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.",
        "'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'.'."
    };
    Glib::RefPtr<Gdk::Pixbuf> pixQ = Gdk::Pixbuf::create_from_xpm_data(quit_xpm);
    Gtk::Image *imgQ = new Gtk::Image(pixQ);
    btQuit = Gtk::manage(new class Gtk::ToolButton(*imgQ, ""));

    toolbar1 = Gtk::manage(new class Gtk::Toolbar());
    vbox1 = Gtk::manage(new class Gtk::VBox(false, 0));
    drWorld = Gtk::manage(new class ZoomRaster(this, observer, xsize, ysize));

    for (auto& var : {btRun, btStep, btView, btGraph, btPict, btQuit}){
        toolbar1->append(*var);
        var->set_visible_horizontal(true);
        var->set_visible_vertical(true);
        var->set_is_important(false);
        var->set_has_tooltip();
    }

    btRun->set_tooltip_text(_("Run"));
    btStep->set_tooltip_text(_("Step"));
    btView->set_tooltip_text(_("View world"));
    btGraph->set_tooltip_text(_("Run graphics"));
    btPict->set_tooltip_text(_("Take a picture"));
    btQuit->set_tooltip_text(_("Quit"));

    toolbar1->set_toolbar_style(Gtk::TOOLBAR_ICONS);
    toolbar1->set_show_arrow(true);
    vbox1->pack_start(*toolbar1, Gtk::PACK_SHRINK, 0);
    vbox1->pack_start(*drWorld);

    set_size_request(5 * xsize, 5 * ysize + toolbar1->get_height() + 5);
    set_title(_("Virtual anthropoids"));
    set_modal(false);
    property_window_position().set_value(Gtk::WIN_POS_CENTER);
    set_resizable(true);
    property_destroy_with_parent().set_value(false);
    add(*vbox1);

    const char * anthropoids_xpm[] = {
        "32 32 16 1",
        " 	c None",
        ".	c #C9AB50",
        "+	c #008000",
        "@	c #990066",
        "#	c #800080",
        "$	c #FF0000",
        "%	c #1900E6",
        "&	c #8D9A3E",
        "*	c #CC9900",
        "=	c #6E9235",
        "-	c #BFA84D",
        ";	c #B3004C",
        ">	c #000000",
        ",	c #DE9900",
        "'	c #660099",
        ")	c #ABA247",
        "                                ",
        " ..........++++++++++.......... ",
        " ......@@@.+###++$$$+......%%%. ",
        " ......@@@.+###++$$$+......%%%. ",
        " ......@@@.+###++$$$+......%%%. ",
        " ..........++++++++++.......... ",
        " &&&&&+++++.....+++++.......... ",
        " &&&&&+%%%+.....+***+.%%%...... ",
        " &&&&&+%%%+.....+***+.%%%...... ",
        " &&&&&+%%%+.....+***+.%%%...... ",
        " &&&&&+++++.....+++++.......... ",
        " .....=====.................... ",
        " .@@@.=====......%%%..%%%...... ",
        " .@@@.=====......%%%..%%%...... ",
        " .@@@.=====......%%%..%%%...... ",
        " .....=====.................... ",
        " &&&&&-----.................... ",
        " &&&&&-----......;;;........... ",
        " &&&&&-->--......;;;........... ",
        " &&&&&-----......;;;........... ",
        " &&&&&-----.................... ",
        " &&&&&&&&&&+++++++++++++++..... ",
        " &&&&&&&&&&+,,,++'''++@@@+..... ",
        " &&&&&&&>&&+,,,++'''++@>@+..... ",
        " &&&&&&&&&&+,,,++'''++@@@+..... ",
        " &&&&&&&&&&+++++++++++++++..... ",
        " &&&&&&&&&&&&&&&)))))+++++..... ",
        " &&&&&&&&&&&&&&&)))))+,,,+..... ",
        " &&&&&&&&&&&&&&&)))))+,,,+..... ",
        " &&&&&&&&&&&&&&&)))))+,,,+..... ",
        " &&&&&&&&&&&&&&&)))))+++++..... ",
        "                                "};

    set_icon(Gdk::Pixbuf::create_from_xpm_data(anthropoids_xpm));

    show_all();

    btRun->signal_clicked().connect(sigc::mem_fun(*this, &Control::on_btRun_clicked), false);
    btStep->signal_clicked().connect(sigc::mem_fun(*this, &Control::on_btStep_clicked), false);
    btView->signal_clicked().connect(sigc::mem_fun(*this, &Control::on_btView_clicked), false);
    btGraph->signal_clicked().connect(sigc::mem_fun(*this, &Control::on_btGraph_clicked), false);
    btPict->signal_clicked().connect(sigc::mem_fun(*this, &Control::on_btPict_clicked), false);
    btQuit->signal_clicked().connect(sigc::mem_fun(*this, &Control::on_btQuit_clicked), false);
    signal_delete_event().connect(sigc::mem_fun(*this, &Control::on_delete), false);

    running = false;
    updateWorld = true;
    setNewSize(drWorld->get_zoom());
}

Control::~Control()
{
    delete btRun;
    delete btStep;
    delete btView;
    delete btGraph;
    delete btPict;
    delete btQuit;
    delete toolbar1;
    delete vbox1;
}

void Control::setNewSize(int zoom)
{
    resize(zoom * WorldXSize * 5,
            zoom * WorldYSize * 5 + toolbar1->get_height());

}

void Control::update()
{
    while (gtk_events_pending())
        gtk_main_iteration();
}

void Control::on_btRun_clicked()
{  
    if(running)
        return;
    running = true;
    theModel->setStatus(2);
    theModel->go();
}

void Control::on_btStep_clicked()
{  
    theModel->setStatus(1);
    if(running){
        running = false;
    } else{
        theModel->go();
    }
}

void Control::on_btView_clicked()
{  
    if(updateWorld){
        updateWorld = false;
        theObserver->setShowWorld(false);
        drWorld->clearCanvas();
    } else{
        updateWorld = true;
        theObserver->setShowWorld(true);
        theObserver->drawWorld();
    }
}

ZoomRaster *Control::getZoomRaster()
{
    return drWorld;
}

void Control::on_btGraph_clicked()
{  
    theModel->setStatus(3);
    if(!running){
        running = true;
        theModel->go();
    }
}

void Control::on_btPict_clicked()
{  
    if(updateWorld)
        theObserver->saveImg();
    else
        warnMsg(_("The image can be created only if the world is visible."));
}

void Control::on_btQuit_clicked()
{  
    theModel->setStatus(0);
    if(updateWorld)
        theObserver->saveImg();
    hide();
}

// when the window is closed
bool Control::on_delete(__attribute__((unused)) GdkEventAny *e) // can't avoid compiler warning on unused parameter
{
    on_btQuit_clicked();
    return true;
}
